version: "3.7"

services:
  node-red:
    build: 
      ./node_red
    environment:
      - TZ=Europe/Moscow
    ports:
      - "1880:1880"
    volumes:
      - ./node_red/data:/data
    user: root:root
    devices:
      - /dev/ttyAMA0:/dev/ttyAMA0
      - /dev/mem:/dev/mem
    privileged: true
    restart: unless-stopped


  mosquitto:
    build:
      ./mosquitto
    ports:
      - "1883:1883"
      - "8883:8883"
    environment:
      - MOSQUITTO_USERNAME=mosquitto
      - MOSQUITTO_PASSWORD=mosquitto
      - PROTOCOL=websockets
    volumes:
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/logs:/mosquitto/logs
      - ./mosquitto/conf:/mosquitto/config
    restart: unless-stopped